# Generated by Django 3.1.1 on 2020-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_in_good_hands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
