# Generated by Django 3.1.1 on 2020-09-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_in_good_hands', '0004_myuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
