# Generated by Django 3.1.1 on 2020-09-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_in_good_hands', '0005_auto_20200914_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
