# Generated by Django 3.1.1 on 2020-09-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_in_good_hands', '0007_auto_20200916_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.CharField(blank=True, choices=[('zabrane', 'zabrane'), ('niezabrane', 'niezabrane')], default='niezabrane', max_length=64),
        ),
    ]
